import React, { useState } from 'react'
import { Box, Button, Chip, Paper, Stack, TextField, Typography } from '@mui/material'
import { CitationDisplay, ConfidenceBadge } from './index'

interface Message { id: string; role: 'user' | 'assistant'; content: string; citations?: any[]; confidence?: 'low' | 'medium' | 'high'; formulation_class?: string | null; requires_escalation?: boolean }
interface ChatInterfaceProps { onSendMessage: (message: string, jurisdiction: string) => Promise<any>; jurisdiction: string; starterQuestions: string[] }

export const ChatInterface: React.FC<ChatInterfaceProps> = ({ onSendMessage, jurisdiction, starterQuestions }) => {
  const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false)
  const send = async (value = input) => { if (!value.trim() || loading) return; setMessages(p => [...p, { id: crypto.randomUUID(), role: 'user', content: value }]); setInput(''); setLoading(true); try { const r = await onSendMessage(value, jurisdiction); setMessages(p => [...p, { id: crypto.randomUUID(), role: 'assistant', content: r.message.content, citations: r.citations, confidence: r.confidence, formulation_class: r.formulation_class, requires_escalation: r.requires_escalation }]) } catch { setMessages(p => [...p, { id: crypto.randomUUID(), role: 'assistant', content: 'The research service is unavailable. No answer was generated; please try again shortly.', confidence: 'low' }]) } finally { setLoading(false) } }
  return <Paper variant="outlined" sx={{ p: { xs: 2, md: 3 } }}><Stack direction="row" justifyContent="space-between" alignItems="flex-start" pb={2} borderBottom="1px solid" borderColor="divider"><Box><Typography variant="overline" color="text.secondary">Ask a research question</Typography><Typography variant="h5">{jurisdiction === 'india' ? 'India legal corpus' : 'International legal corpus'}</Typography></Box><Chip label="Isolated namespace" size="small" color="success" variant="outlined" /></Stack>
    {messages.length === 0 ? <Box textAlign="center" py={5}><Box sx={{ display: 'grid', placeItems: 'center', mx: 'auto', width: 46, height: 46, border: '1px solid', borderColor: 'divider', borderRadius: '50%', color: 'secondary.main', fontSize: 22 }}>⌕</Box><Typography variant="h5" mt={2}>Start with a decision, not a keyword.</Typography><Typography variant="body2" color="text.secondary" mt={.5}>Ask about protection, classification, access-and-benefit sharing, or market entry.</Typography><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(3, 1fr)' }, gap: 1, mt: 3, textAlign: 'left' }}>{starterQuestions.map(question => <Button key={question} variant="outlined" color="primary" onClick={() => send(question)} sx={{ textTransform: 'none', justifyContent: 'space-between', textAlign: 'left', minHeight: 72, fontSize: 12 }}>{question} →</Button>)}</Box></Box> : <Stack spacing={1.5} py={2}>{messages.map(message => <Paper key={message.id} variant={message.role === 'assistant' ? 'outlined' : undefined} sx={{ p: 2, ml: message.role === 'user' ? { xs: 2, sm: 8 } : 0, bgcolor: message.role === 'user' ? 'primary.light' : '#fafbf8' }}><Typography variant="overline" color="text.secondary">{message.role === 'user' ? 'Your question' : 'Grounded response'}</Typography><Typography variant="body2" whiteSpace="pre-wrap" lineHeight={1.75}>{message.content}</Typography>{message.formulation_class && <Chip label={`Formulation path: ${message.formulation_class.replace(/_/g, ' ')}`} size="small" color="success" sx={{ mt: 1.5, textTransform: 'capitalize' }} />}{message.role === 'assistant' && message.citations && <CitationDisplay citations={message.citations} />}{message.role === 'assistant' && message.confidence && <ConfidenceBadge confidence={message.confidence} />}{message.requires_escalation && <Typography variant="caption" display="block" color="#875b17" sx={{ mt: 1 }}>Low confidence: consider a human AYUSH-IP facilitator.</Typography>}</Paper>)}</Stack>}
    <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.25} mt={2}><TextField fullWidth multiline minRows={3} value={input} disabled={loading} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send() } }} placeholder="Ask about an Ayurvedic product, IP right, regulatory pathway or ABS obligation…" /><Button variant="contained" onClick={() => send()} disabled={!input.trim() || loading} sx={{ minWidth: 142 }}>{loading ? 'Researching…' : 'Ask Sahayak →'}</Button></Stack><Typography variant="caption" color="text.secondary" display="block" mt={1}>Enter to send · Shift + Enter for a new line · Answers are grounded only in the selected corpus.</Typography>
  </Paper>
}
